ISL_Season/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from ISL_Season import settings

urlpatterns = [
	path('',include('season.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

season/urls.py
from django.urls import path, re_path
from . import views
#import re

app_name = 'season'

urlpatterns = [
	#start page
	path('',views.StartView.as_view(), name ='start'),

	#match schedule
	path('calendar/',views.CalendarView.as_view(), name ='calendar'),

	#test_page
	path('test_page/',views.TestPageView.as_view(), name = 'test_page'),

	#individual match
	path('match/<int:GameID>/round/<int:GameRound>/',views.MatchView.as_view(), name = 'match'),

	#individual match - squads
	path('match/<int:GameID>/round/<int:GameRound>/squads',views.MatchSquadsView.as_view(), name = 'matchsquads'),

	#individual match - stats
	path('match/<int:GameID>/round/<int:GameRound>/stats',views.MatchStatsView.as_view(), name = 'matchstats'),

	#individual match - table
	path('match/<int:GameID>/round/<int:GameRound>/table',views.MatchTableView.as_view(), name = 'matchtable'),

	#league table
	path('league/',views.LeagueView.as_view(), name = 'league'),

	#cup_tree
	path('cup/',views.CupView.as_view(), name = 'cup'),

	#player_stat
	path('players/',views.PlayersList.as_view(), name = 'players'),
	
	# #individual player_stat
	re_path(r'^players/(?P<Name>[\w\W ]+?)/$',views.PlayerDeatail.as_view(), name = 'player'),

	#team_stat
	path('teams/',views.TeamsList.as_view(), name = 'teams_list'),
	
	# #individual team_stat
	#re_path(r'^teams/(?P<Name>[\w\W ]+?)/$',views.TeamDetail.as_view(), name = 'team_detail'),
	path('teams/<int:pk>/',views.TeamDetail.as_view(), name = 'team_detail'),

	# #update individual team_stat
	#re_path(r'^teams/(?P<Name>[\w\W ]+?)/update/$',views.TeamUpdate.as_view(), name = 'team_update'),
	path('teams/<int:pk>/update/',views.TeamUpdate.as_view(), name = 'team_update'),
	# #individual player_stat
	# path(r'players/<str:id>',views.PlayerView.as_view(), name = 'player'),

	] 

season/forms.py
from django import forms

class Test_pageForm(forms.Form):
	post = forms.IntegerField(max_value = 10, min_value = 0, initial = 0)

class MatchForm(forms.Form):
	GameRound = forms.IntegerField(max_value = 10, min_value = 0, initial = 0)

class HomeForm(forms.Form):
	pass
	#GamesToPlay = forms.IntegerField(max_value = 10, min_value = 0, initial = 0)
		

season/views.py
from django.views import generic
from .models import *
from season.forms import Test_pageForm, MatchForm, HomeForm
from django.shortcuts import render, get_object_or_404, redirect
from season.MatchGenerator import Matchgenerator, Fitness_recovery, Motivation_update, Day_loop, update_cup_schedule, update_division_table
from season.MatchGenerator.DatabaseChanges import Reset_Database
from season.MatchGenerator.DatabaseChanges import Save_and_load_progress
from django.db.models import Avg, Max, Q
from collections import defaultdict
from math import *
import pandas as pd
import numpy as np
import os
 

connection_string = {
    'host': os.environ.get('DB_HOST'),
    'database':'isl',
    'user': os.environ.get('DB_USER'),
    'password':os.environ.get('DB_PASS'),
    'ssl_ca': os.environ.get('SSL_CA_DIR'),
    'ssl_cert': os.environ.get('SSL_CERT_DIR'),
    'ssl_key': os.environ.get('SSL_KEY_DIR')
    }


class StartView(generic.list.ListView):
    template_name = "season/start.html"

    def get(self,request):
        # all_matches = GeneralSchedule.objects.all()
        # days = DayTable.objects.all().filter(Status='Future')
        # current_day = DayTable.objects.get(Status='Current')
        # if current_day ==None:
        #     current_day = DayTable.objects.all().filter(Status='Past').last()
        # weeks = DayTable.objects.all().filter(Status='Future').last()
        # no_of_days = len(days)
        # next_game = GeneralSchedule.objects.filter(Played=False).first()
        context = {}
        return render(request,self.template_name,context)

    def post(self,request):
        if "PlayFullSeason" in request.POST:
            start_day = DayTable.objects.get(Status='Current')
            end_week = DayTable.objects.all().filter(Status='Future').last()
            start_week = start_day.Week
            end_week = end_week.Week + 1

            for week in range(start_week,end_week):
                first_day = DayTable.objects.all().filter(Week=week).first()
                last_day = DayTable.objects.all().filter(Week=week).last()
                
                for day in range(first_day.Day,last_day.Day+1):
                    no_of_matches = len(GeneralSchedule.objects.all().filter(Day = day,Played =False))
                    
                    if no_of_matches > 0:
                        for game in range(0,no_of_matches):
                            Matchgenerator.Full_game(connection_string)

                    Motivation_update.Motivation_update(connection_string, day)
                    Fitness_recovery.Recovery(connection_string, day)
                    
                    Day_loop.Change_of_Day(connection_string, day)

                #update division table
                update_division_table.weekly_update(connection_string,week)
                #update cup schedule
                update_cup_schedule.cup_update(connection_string)

        elif "ReSetGames" in request.POST:
            Reset_Database.ReSetAll()



        return redirect("season:start")


class CalendarView(generic.list.ListView):
    template_name = "season/calendar.html"
    # context_object_name = "all_matches" 
 
    def get(self,request):
        form = HomeForm()
        try:
            current_day = DayTable.objects.get(Status='Current')
        except DayTable.DoesNotExist:
            current_day = DayTable.objects.all().filter(Status='Past').last()
        last_day = current_day.Day-1
        all_matches = GeneralSchedule.objects.filter(Day = current_day.Day)

        Tournaments = Tournament.objects.all().order_by("-id")

        #doesn't work until page is reloaded
        if not all_matches:
            Day_loop.Set_End_of_Day(connection_string, current_day.Day)
            TypeOfDay = "Not Match Day"
            Division_table = None

        last_game = GeneralSchedule.objects.filter(Played=True).last()
        next_game = GeneralSchedule.objects.filter(Played=False).first()

        if all_matches:
            if not next_game:
                if last_game.TournamentName == "Cup":
                    TypeOfDay ="Cup Day"
                    Division_table = None
                else:
                    TypeOfDay ="Division Day"
                    Division_table = TeamDivisionData.objects.all().filter(Tournament_id = next_game.Tournament.id).order_by("Place")
            elif next_game.TournamentName == "Cup":
                TypeOfDay ="Cup Day"
                Division_table = None
            else:
                TypeOfDay ="Division Day"
                Division_table = TeamDivisionData.objects.all().filter(Tournament_id = next_game.Tournament.id).order_by("Place")

        all_players_fitness = PlayerFitnessLog.objects.all().filter(Day= last_day, TypeOfUpdate = "Dayly").order_by("-FitnessChange")[:10]

        Current_week = current_day.Week
        Current_week_days = [Current_week*7-6,Current_week*7-5,Current_week*7-4,Current_week*7-3,Current_week*7-2,Current_week*7-1,Current_week*7]
        
        context = {
                'form':form,
                'all_matches':all_matches,
                'next_game':next_game,
                'last_game':last_game,
                'current_day':current_day,
                "Current_week_days":Current_week_days,
                "all_players_fitness":all_players_fitness,
                "last_day":last_day,
                "Tournaments":Tournaments,
                'Division_table':Division_table,
                "TypeOfDay":TypeOfDay
                }
        return render(request,self.template_name,context)

    def post(self,request):
        form = HomeForm(request.POST)
        current_day = DayTable.objects.get(Status='Current')
        next_day = DayTable.objects.get(Status='Next')
        next_game = GeneralSchedule.objects.filter(Played=False).first()

        if "ReSetGames" in request.POST:
            Reset_Database.ReSetAll()

        elif "PlayNextGame" in request.POST:
            #Check if next game is on a new day in that case show end of day form
            if next_game.Day > current_day.Day:
                Day_loop.Set_End_of_Day(current_day.Day)
            else:
                Matchgenerator.Full_game(connection_string)
                Tournaments = Tournament.objects.all()

                for T in Tournaments:
                    T.collapse()
                    # T.calendar_class = "btn btn-link collapsed"
                    # T.calendar_expanded = "false"
                    # T.calendar_div_class = "collapse"

                next_game.Tournament.expand()



        elif "PlayFullDay" in request.POST:
            #Check if next game is on a new day in that case show end of day form
            if next_game.Day > current_day.Day:
                Day_loop.Set_End_of_Day(connection_string,current_day.Day)
            else:
                no_of_matches = len(GeneralSchedule.objects.all().filter(Day = current_day.Day,Played =False))
                for x in range(0,no_of_matches):
                    Matchgenerator.Full_game(connection_string)

        elif "Endday" in request.POST:
            Motivation_update.Motivation_update(connection_string, current_day.Day)
            Fitness_recovery.Recovery(connection_string, current_day.Day)
            #check if it's the end of the week
            if next_day.Week > current_day.Week:
                Day_loop.Set_End_of_Week(connection_string, current_day.Day)
                Day_loop.Remove_End_of_Day(connection_string, current_day.Day)
            else:
                Day_loop.Remove_End_of_Day(connection_string, current_day.Day)
                Day_loop.Change_of_Day(connection_string, current_day.Day)

        elif "EndWeek" in request.POST:
            #update division table
            update_division_table.weekly_update(connection_string, current_day.Week)
            #update cup schedule
            update_cup_schedule.cup_update(connection_string)

            #update next week
            Day_loop.Remove_End_of_Week(connection_string, current_day.Day)
            #update day
            Day_loop.Remove_End_of_Day(connection_string, current_day.Day)
            Day_loop.Change_of_Day(connection_string, current_day.Day)
            Tournaments = Tournament.objects.all()

            for T in Tournaments:
                T.collapse()
                # T.calendar_class = "btn btn-link collapsed"
                # T.calendar_expanded = "false"
                # T.calendar_div_class = "collapse"

            next_game.Tournament.expand()

        # elif "UntilDay" in request.POST:
        #     #End day
        #     #if same day - stop

        #     #For day
        #     #play remaining games
        #     #end day procedure
        #     #if new week
        #     #end week procedure
        #     #Change day
        #     #stop when End day = current day


        return redirect("season:calendar")
       

class MatchView(generic.TemplateView):
    template_name = "season/match.html"

    def get(self,request,GameID,GameRound):
        form = MatchForm()
        schedule = GeneralSchedule.objects.get(GameID = GameID)
        Home_team_name = schedule.Home
        Away_team_name = schedule.Away
        Home_team = Team.objects.get(Name = Home_team_name)
        Away_team = Team.objects.get(Name = Away_team_name)
        Home_team_background = TeamInfo.objects.get(Name = Home_team_name)
        Away_team_background = TeamInfo.objects.get(Name = Away_team_name)
        NextRound = GameRound + 1
        CurrentPage ="Match"
        Played = schedule.Played
        if Played == True:
            all_rounds_so_far = GameTeamLog.objects.all().filter(GameID = GameID, GameRound__lte=GameRound) 
            if GameRound > 0:
                current_round = GameTeamLog.objects.all().filter(GameID = GameID, GameRound=GameRound).first
                context = {'Played':Played,
                'form':form,
                'all_rounds_so_far':all_rounds_so_far,

templates/season/_match_header.html
{% load staticfiles %}
<div class="col-sm-3" id="home_team">
	<div class="col-sm-8 mx-auto team_logo_div">
		<img src="{{Home_team.Logo.url}}" alt="home_team_logo" class="img-fluid rounded-circle">
	</div>
	<div class="text-center team_name_div">
		<span>{{Home_team.Name}}</span>
	</div>
</div> 
<div class="col-sm-3" id="result">
	{% if Played == True %}
		<div class="col-sm-12 text-center" id="result_score_div">
			<span>
				{% if current_round%}
					{{current_round.GoalsForwardAfterRound}} - {{current_round.GoalsAgainstAfterRound}}
				{% else %}
					0 - 0
				{% endif %}
			</span>
		</div> 
		<div class="col-sm-12 text-center" id="result_round_div">
			<span>Round</span>
			<span>{{GameRound}}</span>
		</div>
			<div class="col-sm-12 text-center" id="result_round_div">
					{% if CurrentPage == "Match" %}
						{% if GameRound == 10 %}
							<a href="{% url "season:match" GameID=GameID GameRound=0 %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Re-set</button></a>
						{% else %}
							<a href="{% url "season:match" GameID=GameID GameRound=NextRound %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Next</button></a>
							<a href="{% url "season:match" GameID=GameID GameRound=0 %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Re-set</button></a>
						{% endif %}
					{% elif CurrentPage == "Squad" %}
						{% if GameRound == 10 %}
							<a href="{% url "season:matchsquads" GameID=GameID GameRound=0 %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Re-set</button></a>
						{% else %}
							<a href="{% url "season:matchsquads" GameID=GameID GameRound=NextRound %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Next</button></a>
							<a href="{% url "season:matchsquads" GameID=GameID GameRound=0 %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Re-set</button></a>
						{% endif %}	 
					{% elif CurrentPage == "Stats" %}
						{% if GameRound == 10 %}
							<a href="{% url "season:matchstats" GameID=GameID GameRound=0 %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Re-set</button></a>
						{% else %}
							<a href="{% url "season:matchstats" GameID=GameID GameRound=NextRound %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Next</button></a>
							<a href="{% url "season:matchstats" GameID=GameID GameRound=0 %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Re-set</button></a>
						{% endif %}		
					{% elif CurrentPage == "Table" %}
						{% if GameRound == 10 %}
							<a href="{% url "season:matchtable" GameID=GameID GameRound=0 %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Re-set</button></a>
						{% else %}
							<a href="{% url "season:matchtable" GameID=GameID GameRound=NextRound %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Next</button></a>
							<a href="{% url "season:matchtable" GameID=GameID GameRound=0 %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden = "true"></span>Re-set</button></a>
						{% endif %}			   
					{% endif %}
			</div>
	{% else %}
		<div class="col-sm-12 text-center" id="result_score_div">
			<span>
			</span>
		</div>
		<div class="col-sm-12 text-center" id="result_round_div">
			<span>Game not started</span>
			<span></span>
		</div>
		<div class="col-sm-12 text-center" id="result_round_div">
		</div>
	{% endif %}

	<span></span>
</div>
<div class="col-sm-3" id="away_team">
	<div class="col-sm-8 mx-auto team_logo_div">
		<img src="{{Away_team.Logo.url}}" alt="away_team_logo" class="img-fluid rounded-circle">
	</div>
	<div class="text-center team_name_div">
		<span>{{Away_team.Name}}</span>
	</div>
</div>

templates/season/_match_menu.html
{% load staticfiles %}

<ul class="nav nav-pills">

	{% if Played == True %}
		<li class="nav-item">
			{% if CurrentPage == "Match"  %}
				<a class="nav-link active" href="{% url "season:match" GameID=GameID GameRound=GameRound %}">Score</a>
			{% else %}
				<a class="nav-link" href="{% url "season:match" GameID=GameID GameRound=GameRound %}">Score</a>    
			{% endif %}
		</li>
		<li class="nav-item">
			{% if CurrentPage == "Squad" %}
				<a class="nav-link active" href="{% url "season:matchsquads" GameID=GameID GameRound=GameRound %}">Squads</a>	 
			{% else %}
				<a class="nav-link" href="{% url "season:matchsquads" GameID=GameID GameRound=GameRound %}">Squads</a>	  
			{% endif %}			
		</li>
		<li class="nav-item">
			{% if CurrentPage == "Stats" %}
				<a class="nav-link active" href="{% url "season:matchstats" GameID=GameID GameRound=GameRound %}">Stats</a>
			{% else %}
				<a class="nav-link" href="{% url "season:matchstats" GameID=GameID GameRound=GameRound %}">Stats</a>  
			{% endif %}	
		</li>
		<li class="nav-item">
			{% if CurrentPage == "Table" %}
				<a class="nav-link active" href="{% url "season:matchtable" GameID=GameID GameRound=GameRound %}">Table</a>
			{% else %}
				<a class="nav-link" href="{% url "season:matchtable" GameID=GameID GameRound=GameRound %}">Table</a>  
			{% endif %}	
		</li>

	{% else %}
		<li class="nav-item">
			{% if CurrentPage == "Team background"  %}
				<a class="nav-link active" href="{% url "season:match" GameID=GameID GameRound=GameRound %}">Game info</a>
			{% else %}
				<a class="nav-link" href="{% url "season:match" GameID=GameID GameRound=GameRound %}">Game info</a>    
			{% endif %}
		</li>
		<li class="nav-item">
			{% if CurrentPage == "Squads" %}
				<a class="nav-link active" href="{% url "season:matchsquads" GameID=GameID GameRound=GameRound %}">Squads</a>	 
			{% else %}
				<a class="nav-link" href="{% url "season:matchsquads" GameID=GameID GameRound=GameRound %}">Squads</a>	  
			{% endif %}			
		</li>
		<li class="nav-item">
			{% if CurrentPage == "Stats" %}
				<a class="nav-link active" href="{% url "season:matchstats" GameID=GameID GameRound=GameRound %}">Stats</a>
			{% else %}
				<a class="nav-link" href="{% url "season:matchstats" GameID=GameID GameRound=GameRound %}">Stats</a>  
			{% endif %}	
		</li>
		<li class="nav-item">
			{% if CurrentPage == "Tournament info" %}
				<a class="nav-link active" href="{% url "season:matchtable" GameID=GameID GameRound=GameRound %}">Table</a>
			{% else %}
				<a class="nav-link" href="{% url "season:matchtable" GameID=GameID GameRound=GameRound %}">Table</a>  
			{% endif %}	
		</li>

	{% endif %}





</ul>

 

templates/season/base.html
<!DOCTYPE html> 
<html>
<head>
	<title>{% block title %}
	 ISL{% endblock title %}</title>
	<!---load path to static file-->
	{% load static %}
	<!---Bootstrap-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<!---Goodle fonts-->
	<link href="https://fonts.googleapis.com/css?family=Sarpanch" rel="stylesheet">
	<!---Generic blue print-->
	<link rel="stylesheet" type="text/css" href="{% static 'season/style.css' %}">
  <!---Jquery-->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!---?-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <!---Bootstrap's javascript-->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

 {% block extrahead %}{% endblock %}
</head>
<body> 
	<nav class="navbar navbar-expand-sm navbar-dark bg-dark base_navbar">
      <a class="navbar-brand" href="{% url 'season:start' %}">ISL</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'season:calendar' %}">Calendar <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'season:league' %}">League Table</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'season:cup' %}">Cup Tree</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'season:players' %}">Player stats</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'season:teams_list' %}">Team stats</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'season:test_page' %}">Test_page</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-toggler-right">
        	<li class="nav-item">
        		<a class="nav-link" href="#">Logout</a>
        	</li>
        </ul>
      </div>
    </nav>
	{% block body_block %}{% endblock body_block %}
  {% block extra_JS %}{% endblock extra_JS %}
</body>
</html>

templates/season/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{field.errors}}</span>
		</div>
		<label class="control-lable col-sm-2">{{field.label_tag}}</label>
		<div class="col-sm-10"> {{field}}</div>	
	</div>


{% endfor %}

templates/season/match_table.html
{% extends "season/base.html" %}

<!--la till load staticfiles för att det inte fungerar att använda static inom block taggar. i ett senare skede bör logo vara ett attribut till class istället för att använda static-->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'season/style_match.css' %}">
{% block title %}Match{% endblock title %}

{% block body_block %}
<div class="container">
	<div class="row">
		{% include 'season/_match_header.html' %}
	</div>
	<div class="row">
		{% include 'season/_match_menu.html' %}
	</div>
	<div class="row">
		<div class="col-sm-12">

			
		</div>
	</div>
</div>
{% endblock %}

templates/season/players.html
{% extends "season/base.html" %}


{% block body_block %}


	{%if all_players%}
	<h3>list of all players</h3>
	<ul>
		{%for player in all_players %}
		<li><a href="{% url "season:player" Name=player.Name%}"> {{ player }}</a></li>
		{% endfor %}
	</ul>
	{% else %}
		<h3>No players to display</h3>
	{% endif %}

{% endblock body_block %} 

templates/season/teamdetail.html
{% extends "season/base.html" %}
{% load static %}
{% block extrahead %}
	<link rel="stylesheet" type="text/css" href="{% static 'season/team_detail.css' %}">
{% endblock %}

{% block body_block %}

<div class="grid-container">
  <div class="grid-item grid-header">
  	<div>		
		<h1>{{team.Name}} <span class="badge badge-info">{{team.Division}}</span></h1>
	</div>
	<div>
		<h5>{{team.FullName}}</h5>
	</div>
  </div>
  <div class="grid-item grid-logo">
  	<div>
		{% if team.Logo %}
			<img class="logo" src="{{team.Logo.url}}">  
		{% endif %}
	</div>
  </div>
  <div class="grid-item item3">
  	<h2>Background</h2>
	<p>{{teaminfo.Background}}</p>
  </div>
  <div class="grid-item item4">
  	<h2>Stadium</h2>
	<p>{{teaminfo.Arena}}</p>
	<p>{{teaminfo.ArenaDescription}}</p>
  </div>
  <div class="grid-item item5">
  	<h2>Fan Club</h2>
	<p>{{teaminfo.FanClub}}</p>
	<p>{{teaminfo.FanClubDescription}}</p>
  </div>
  <div class="grid-item item6">
  	<h2>Junior team</h2>
  </div>
  <div class="grid-item item7">7</div>
  <div class="grid-item item8">8</div>
</div>


<div>
	<a href="{% url "season:team_update" pk=team.pk%}"><button>Update</button></a>
</div>
<div class="row">
	<div>		
		<p>{{team.Name}}</p>
	</div>
	<div>
		<p>{{team.FullName}}</p>
	</div>
	<div>
		{% if team.Logo %}
			<img class="logo" src="{{team.Logo.url}}">  
		{% endif %}
	</div>
</div>
<div>
	<h2>info</h2>
	<p>{{teaminfo.Background}}</p>
</div>
<div>
	<p>{{team.Division}}</p>
</div>
<div>		
	<h2>Stadium</h2>
	<p>{{teaminfo.Arena}}</p>
	<p>{{teaminfo.ArenaDescription}}</p>
</div>
<div>
	<h2>Fan Club</h2>
	<p>{{teaminfo.FanClub}}</p>
	<p>{{teaminfo.FanClubDescription}}</p>
</div>


{% endblock body_block %} 

templates/season/teamlist.html
{% extends "season/base.html" %}


{% block body_block %}


	{%if all_teams%}
	<h3>list of all teams</h3>
	<ul>
		{%for team in all_teams %}
		<li><a href="{% url "season:team_detail" pk=team.pk%}"> {{ team }}</a></li>
		{% endfor %}
	</ul>
	{% else %}
		<h3>No players to teams</h3>
	{% endif %}

{% endblock body_block %} 